---

- name: Install prerequisites on OpenSUSE < 15.3
  package:
    name:
      #- libssl45
      #- libgssglue1
      #- libX11-6
      - xauth
      - mozilla-nspr
      - mozilla-nss
      - ghostscript
      - sendmail
      #- python2-ldap
      #- python
      #- python-xml
    state: latest
  when: ( 
          ( ansible_distribution_major_version | int == 15 ) and
          ( ansible_distribution_release | int < 3 ) and
          ( ansible_distribution | lower is search("opensuse") )
        )

- name: Install prerequisites on OpenSUSE 15.3
  package:
    name:
      #- libgssglue1
      #- libX11-6
      - xauth
      - mozilla-nspr
      - mozilla-nss
      - ghostscript
      - sendmail
      #- python2-ldap
      #- python3
      #- python-xml
      - nfs-client
      - python3-gobject
      - typelib-1_0-Gtk-3_0
    state: latest
  when: ( 
          ( ansible_distribution_major_version | int == 15 ) and
          ( ansible_distribution_release | int ==  3 ) and
          ( ansible_distribution | lower is search("opensuse") )
        )

###########################################################################
#
# on SUSE it's required to inlcude the following repos using SUSEConnect
#
# Desktop Applications Module 15 SP2 x86_64 
# Activate with: SUSEConnect -p sle-module-desktop-applications/15.2/x86_64
#
# Python 2 Module 15 SP2 x86_64 
# Activate with: SUSEConnect -p sle-module-python2/15.2/x86_64
#
# Check with: SUSEConnect --list
#
###########################################################################

- name: Install prerequisites on SLES
  package:
    name:
      - libgssglue1
      - libX11-6
      - xauth
      - mozilla-nspr
      - mozilla-nss
      - ghostscript
      #- python2-ldap
      #- python
      #- python-xml
    state: latest
  when: ( ansible_distribution_major_version | int == 15 ) and
        ( ansible_distribution | lower is search("sles") )
