---
- name: Check if we can do a inventory
  setup:
    gather_subset: min
  failed_when: false
  register: minimal

- block:

  - name: Verify python installation
    #raw: python -V || python2 -V || python3 -V
    raw: python3 -V
    failed_when: false
    changed_when: false
    register: python_installed
  
  - name: Try to install python
    include_tasks: pre_python.yml
    when: python_installed.rc != 0
  
  - meta: clear_facts

  - name: Init facts
    setup:
    #vars:
    #      ansible_python_interpreter: /usr/bin/python3

  when: ( ansible_distribution_file_variety is not defined ) or ( minimal.rc is defined and minimal.rc != 0 )

- set_fact:
     incname: "pre_{{ ansible_distribution_file_variety | lower | map('trim') | join }}.yml"

# https://github.com/ansible/ansible/pull/74530
- name: Rocky/Alma Linux workaround
  set_fact:
    ansible_os_family: "RedHat"
  when: ansible_distribution == "Rocky" or
        ansible_distribution == "AlmaLinux"

- name: Copy /usr/etc/pam.d/sshd
  include_tasks: "copy_usr_etc_pam_sshd.yml"

- name: Link /usr/etc/ssh/sshd_config
  include_tasks: "link_usr_etc_sshd.yml"

- name: Trying to find distribution prerequisites 
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ incname }}"
    - "default.yml"
