---

- debug: var=ansible_distribution_release

#
# Debian
#
- name: Allow release-info to change for APT repositories
  command: apt-get update -y --allow-releaseinfo-change
  when:  ansible_distribution_release is defined and ansible_distribution_release == "buster" 
